@startuml
hide empty members
skinparam linetype polyline
skinparam arrowLollipopColor #ADD1B2

MainView -left(0- MainPresenter : IMainContract.Presenter
MainView -left0)- MainPresenter : IMainContract.View
MainView -up..-> InfoView : <<use>>
MainView -down..-> ConsultarView : <<use>>
MainView -down..->RegistrarView : <<use>>
MainView -left..->RegistrarDescuentoView : <<use>>
MainView -left..> DetailsView : <<use>>
MainPresenter -left(0- GasolinerasRepository : IGasolinerasRepository
RegistrarPresenter -down(0- RepostajeDAO : IRepostajeDAO
ConsultarPresenter -down(0- RepostajeDAO : IRepostajeDAO
RegistrarDescuentoPresenter -down(0- DescuentoDAO : IDescuentoDAO
RegistrarView -right(0- RegistrarPresenter : IRegistrarContract.Presenter
RegistrarView -right(0- RegistrarPresenter : IRegistrarContract.View
ConsultarView -right(0- ConsultarPresenter : IConsultarContract.Presenter
ConsultarView -right(0- ConsultarPresenter : IConsultarContract.View
RegistrarDescuentoView -left(0- RegistrarDescuentoPresenter : IRegistrarDescuentoContract.View
RegistrarDescuentoView -left(0- RegistrarDescuentoPresenter : IRegistrarDescuentoContract.Presenter
DetailsView -down(0- DetailsPresenter : IDetailsContract.Presenter
DetailsView -down(0- DetailsPresenter : IDetailsContract.View
DetailsPresenter -up(0- DescuentoDAO : IDescuentoDAO
DetailsPresenter -right(0- GasolinerasRepository : IGasolinerasRepository

class MainPresenter {
    - load()
    + activarFiltro(String municipio) : String
    + hayFiltroActivado() : String 
    + hayOrdenamientoPrivado(): String
    + activarOrdenamiento(): boolean
}

class RegistrarPresenter {
    + RegistrarPresenter(RepostajeDAO repostajeDAO)

}
class ConsultarPresenter {
    - load()
    + calculaPrecioMedioLitro(): double
    + obtenerRepostajesDelMes(): List<Repostaje>
    + calcularAcumuladoMes(): double
}

class RegistrarDescuentoPresenter {
    
}

class DetailsPresenter {
   - load()
   - obtenerNombreDelDia(LocalDate fechaActual): String
   - requestGasolineras(LocalDate fecha, ICallBack callBack)
}


interface IDetails#View {
    + init()
    + onOptionsItemSelected(MenuItem item): boolean
    + getGasolinerasRepository():  IGasolinerasRepository
    + mostrarPrecioGasolina95SemanaPasada(double precioSemanaPasada, Descuento descuento)
    + mostrarPrecioDieselSemanaPasada(double precioSemanaPasada, Descuento descuento)
    + mostrarDiaDeLaSemana(String texto)
    + mostrarError(String mensaje)
    + mostrarPreciosActuales(Descuento descuento)
}


interface IDetails#Presenter {
    + init()
}


interface IMainContract#View {
    + init()
    + getGasolinerasRepository() : IGasolinerasRepository
    + showStations(List<Gasolinera> stations)
    + showLoadCorrect(int stations)
    + showLoadError()
    + showStationDetails(Gasolinera station)
    + showInfoActivity()
    + showConsultarActivity()
    + showRegistrarActivity()
    + showDescuentoActivity()
    + mostrarErrorNoGasolinerasEnMunicipio(String s)
    + showBtnCancelarFiltro()
    + getDescuentoDatabase() : DescuentoDAO

}

interface IMainContract#Presenter {
    + init(View view)
    + onStationClicked(Gasolinera station)
    + onMenuInfoClicked()
    + onMenuRegistrarClicked()
    + onMenuConsultarClicked()
    + onMenuDescuentoClicked()
    + onBtnFiltrarClicked()
    + onBtnCancelarFiltroClicked()
    + onBtnOrdenarClicked()
}

interface IGasolinerasRepository {
    + requestGasolineras(ICallBack cb, String ccaa)
}


interface IRegistrar#View {
    + init()
    + mostrarError(String mensajeError, boolean errorLitros, boolean errorPrecioTotal)
    +showBtnGuardar(String litros, String precioTotal)
    +showBtnCancelar()
}

interface IRegistrar#Presenter {
    + init(View view)
    + onBtnGuardarClicked(String litros,String precioTotal)
    + onBtnCancelarClicked()
}

interface IConsultar#View {
    + init()
    + showRepostajes(List<Repostajes> repostajes)
    + showLoadCorrect(int reepostajes)
    + showLoadError()
    + showCalculosRepostajes()
    
}

interface IConsultar#Presenter {
    + init()
}

interface IRegistrarDescuento#Presenter {
    + init(View view)
    + onBtnGuardarClicked(String marca, double descuento)
    + onBtnCancelarClicled()
}

interface IRegistrarDescuento#View {
    + init()
    + showBtnGuardar(String marca, double descuento)
    + showBtnCancelar()
    + mostrarError(String mensajeError, boolean errorDescuento)
}



interface ICallBack {
    + onSuccess(List<Gasolinera> gasolineras)
    + onFailure(Throwable e)
}

interface RepostajeDAO {
}

interface DescuentoDAO {
}
@enduml